backend:
  name: git-gateway
  branch: master
  repo: ogdendavis/denver-kitchen-gardens

media_folder: 'static/images/uploads'
public_folder: '/images/uploads'

collections:
  - name: 'general'
    label: 'General Info'
    files:
      - name: 'site'
        label: 'Site Identity'
        file: 'src/cms/general/site.md'
        fields:
          - { label: 'Header Logo', name: 'header_logo', widget: 'image' }
      - name: 'contact'
        label: 'Contact Info'
        file: 'src/cms/general/contact.md'
        fields:
          - { label: 'Phone', name: 'phone', widget: 'string' }
          - { label: 'Instagram', name: 'instagram', widget: 'string' }
  - name: 'pages'
    label: 'Main Pages'
    files:
      - name: 'home'
        label: 'Home'
        file: 'src/cms/pages/home.md'
        fields:
          - { label: 'Hero Image', name: 'hero', widget: 'image' }
          - { label: 'Headline', name: 'title', widget: 'string' }
          - { label: 'Hero Text', name: 'hero_text', widget: 'text' }
          - { label: 'Intro Image', name: 'intro_image', widget: 'image' }
          - { label: 'Intro Heading', name: 'intro_heading', widget: 'string' }
          - { label: 'Intro Copy', name: 'intro_copy', widget: 'markdown' }
          - {
              label: 'Mission Copy - above pullquote',
              name: 'above_pullquote',
              widget: 'markdown',
            }
          - {
              label: 'Mission Copy - pullquote',
              name: 'pullquote',
              widget: 'text',
            }
          - {
              label: 'Mission Copy - below pullquote',
              name: 'below_pullquote',
              widget: 'markdown',
            }
          - {
              label: 'Portfolio Heading',
              name: 'portfolio_heading',
              widget: 'string',
            }
          - {
              label: 'Portfolio Subheading',
              name: 'portfolio_subheading',
              widget: 'text',
            }
      - name: 'services'
        label: 'Services'
        file: 'src/cms/pages/services.md'
        fields:
          - { label: 'Hero Image', name: 'hero', widget: 'image' }
          - { label: 'Headline', name: 'title', widget: 'string' }
          - { label: 'Hero Text', name: 'hero_text', widget: 'text' }
          - {
              label: 'Services Heading',
              name: 'services_heading',
              widget: 'string',
            }
          - {
              label: 'Next Steps Heading',
              name: 'nextsteps_heading',
              widget: 'string',
            }
          - {
              label: 'Next Steps Copy',
              name: 'nextsteps_copy',
              widget: 'markdown',
            }
      - name: 'work'
        label: 'Portfolio'
        file: 'src/cms/pages/work.md'
        fields:
          - { label: 'Headline', name: 'title', widget: 'string' }
          - { label: 'Hero Text', name: 'hero_text', widget: 'text' }
          - {
              label: 'Interbutton Link',
              name: 'interbutton_link',
              widget: 'string',
            }
          - {
              label: 'Interbutton Text',
              name: 'interbutton_text',
              widget: 'string',
            }
          - {
              label: 'Bottom Button Link',
              name: 'bottombutton_link',
              widget: 'string',
            }
          - {
              label: 'Bottom Button Text',
              name: 'bottombutton_text',
              widget: 'string',
            }
      - name: 'faq'
        label: 'FAQ'
        file: 'src/cms/pages/faq.md'
        fields:
          - { label: 'Headline', name: 'title', widget: 'string' }
          - { label: 'Hero Text', name: 'hero_text', widget: 'text' }
          - label: 'Questions'
            name: 'questions'
            widget: 'list'
            fields:
              - { label: 'Question', name: 'question', widget: 'text' }
              - { label: 'Answer', name: 'answer', widget: 'markdown' }
      - name: 'about'
        label: 'About'
        file: 'src/cms/pages/about.md'
        fields:
          - { label: 'Hero Image', name: 'hero', widget: 'image' }
          - { label: 'Headline', name: 'title', widget: 'string' }
          - { label: 'Hero Text', name: 'hero_text', widget: 'text' }
          - {
              label: 'Content Heading',
              name: 'content_heading',
              widget: 'string',
            }
          - { label: 'Content Copy', name: 'content_copy', widget: 'markdown' }
          - { label: 'Profile Image', name: 'profile_pic', widget: 'image' }
          - label: 'Additional Images'
            name: 'more_pics'
            widget: 'list'
            fields:
              - { label: 'Image', name: 'image', widget: 'image' }
      - name: 'contact'
        label: 'Contact'
        file: 'src/cms/pages/contact.md'
        fields:
          - { label: 'Hero Image', name: 'hero', widget: 'image' }
          - { label: 'Headline', name: 'title', widget: 'string' }
          - { label: 'Hero Text', name: 'hero_text', widget: 'text' }
          - { label: 'Form Heading', name: 'form_heading', widget: 'string' }
          - { label: 'Form Button Text', name: 'form_button', widget: 'string' }
  - name: 'services'
    label: 'Service Pages'
    label_singular: 'Service Page'
    folder: 'src/cms/service_pages'
    create: true
    slug: '{{slug}}'
    fields:
      - {
          label: 'Published',
          name: 'published',
          widget: 'boolean',
          default: false,
        }
      - { label: 'Service Name', name: 'title', widget: 'string' }
      - { label: 'Preview Text', name: 'preview_text', widget: 'text' }
      - { label: 'Preview Image', name: 'preview_image', widget: 'image' }
      - { label: 'Header Image', name: 'header_image', widget: 'image' }
      - {
          label: 'Intro Subheading',
          name: 'intro_subheading',
          widget: 'string',
        }
      - { label: 'Intro Copy', name: 'intro_copy', widget: 'markdown' }
      - {
          label: 'Detail Heading',
          name: 'detail_heading',
          widget: 'string',
          required: false,
        }
      - {
          label: 'Detail Copy',
          name: 'detail_copy',
          widget: 'markdown',
          required: false,
        }
      - { label: 'Process Heading', name: 'process_heading', widget: 'string' }
      - label: 'Process Points'
        name: 'process_points'
        widget: 'list'
        fields:
          - { label: 'Point Title', name: 'point_title', widget: 'string' }
          - { label: 'Point text', name: 'point_text', widget: 'text' }
      - {
          label: 'Call to Action Text',
          name: 'call_text',
          widget: 'text',
          required: false,
        }
      - {
          label: 'Call to Action Button Link',
          name: 'call_url',
          widget: 'string',
          required: false,
        }
      - {
          label: 'Call to Action Button Text',
          name: 'call_button',
          widget: 'string',
          required: false,
        }
  - name: 'projects'
    label: 'Projects'
    label_singular: 'Project'
    folder: 'src/cms/projects'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Project Name', name: 'title', widget: 'string' }
      - label: 'Images'
        name: 'images'
        widget: 'list'
        fields:
          - { label: 'Image', name: 'image', widget: 'image' }
