backend:
  name: git-gateway
  branch: master
  repo: ogdendavis/denver-kitchen-gardens

media_folder: 'static/images/uploads'
public_folder: '/images/uploads'

# Start with service pages
collections:
  - name: 'pages'
    label: 'Main Pages'
    files:
      - name: 'home'
        label: 'Home'
        file: 'src/cms/pages/home.md'
        fields:
          - { label: 'Headline', name: 'title', widget: 'string' }
          - { label: 'Hero Image', name: 'hero', widget: 'image' }
          - { label: 'Content', name: 'content', widget: 'markdown' }
      - name: 'about'
        label: 'About'
        file: 'src/cms/pages/about.md'
        fields:
          - { label: 'Headline', name: 'title', widget: 'string' }
          - { label: 'Main Image', name: 'image', widget: 'image' }
          - { label: 'Content', name: 'content', widget: 'markdown' }
      - name: 'work'
        label: 'Work'
        file: 'src/cms/pages/work.md'
        fields:
          - { label: 'Headline', name: 'title', widget: 'string' }
          - { label: 'Main Image', name: 'image', widget: 'image' }
          - { label: 'Content', name: 'content', widget: 'markdown' }
      - name: 'contact'
        label: 'Contact'
        file: 'src/cms/pages/contact.md'
        fields:
          - { label: 'Headline', name: 'title', widget: 'string' }
          - { label: 'Main Image', name: 'image', widget: 'image' }
          - { label: 'Content', name: 'content', widget: 'markdown' }
  - name: 'services'
    label: 'Service Pages'
    label_singular: 'Service Page'
    folder: 'src/cms/service_pages'
    create: true
    slug: '{{slug}}'
    fields:
      - {
          label: 'Published',
          name: 'published',
          widget: 'boolean',
          default: false,
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Main Image', name: 'image', widget: 'image' }
      - { label: 'Content', name: 'content', widget: 'markdown' }
