backend:
  name: git-gateway
  branch: master
  repo: ogdendavis/denver-kitchen-gardens

media_folder: 'static/images/uploads'
public_folder: '/images/uploads'

collections:
  - name: 'general'
    label: 'General Info'
    files:
      - name: 'site'
        label: 'Site Identity'
        file: 'src/cms/general/site.md'
        fields:
          - { label: 'Header Logo', name: 'header_logo', widget: 'image' }
          - { label: 'Footer Logo', name: 'footer_logo', widget: 'image' }
          - { label: 'Footer Text', name: 'body', widget: 'markdown' }
      - name: 'contact'
        label: 'Contact Info'
        file: 'src/cms/general/contact.md'
        fields:
          - { label: 'Phone', name: 'phone', widget: 'string' }
          - { label: 'Instagram', name: 'instagram', widget: 'string' }
  - name: 'pages'
    label: 'Main Pages'
    files:
      - name: 'home'
        label: 'Home'
        file: 'src/cms/pages/home.md'
        fields:
          - { label: 'Hero Image', name: 'hero', widget: 'image' }
          - { label: 'Headline', name: 'title', widget: 'string' }
          - { label: 'Hero Text', name: 'hero_text', widget: 'text' }
          - { label: 'Content', name: 'body', widget: 'markdown' }
      - name: 'services'
        label: 'Services'
        file: 'src/cms/pages/services.md'
        fields:
          - { label: 'Hero Image', name: 'hero', widget: 'image' }
          - { label: 'Headline', name: 'title', widget: 'string' }
          - { label: 'Hero Text', name: 'hero_text', widget: 'text' }
          - { label: 'Content', name: 'body', widget: 'markdown' }
      - name: 'work'
        label: 'Portfolio'
        file: 'src/cms/pages/work.md'
        fields:
          - { label: 'Headline', name: 'title', widget: 'string' }
          - { label: 'Hero Text', name: 'hero_text', widget: 'text' }
          - { label: 'Content', name: 'body', widget: 'markdown' }
      - name: 'about'
        label: 'About'
        file: 'src/cms/pages/about.md'
        fields:
          - { label: 'Hero Image', name: 'hero', widget: 'image' }
          - { label: 'Headline', name: 'title', widget: 'string' }
          - { label: 'Hero Text', name: 'hero_text', widget: 'text' }
          - { label: 'Content', name: 'body', widget: 'markdown' }
      - name: 'contact'
        label: 'Contact'
        file: 'src/cms/pages/contact.md'
        fields:
          - { label: 'Hero Image', name: 'hero', widget: 'image' }
          - { label: 'Headline', name: 'title', widget: 'string' }
          - { label: 'Hero Text', name: 'hero_text', widget: 'text' }
          - { label: 'Content', name: 'body', widget: 'markdown' }
  - name: 'services'
    label: 'Service Pages'
    label_singular: 'Service Page'
    folder: 'src/cms/service_pages'
    create: true
    slug: '{{slug}}'
    fields:
      - {
          label: 'Published',
          name: 'published',
          widget: 'boolean',
          default: false,
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Main Image', name: 'image', widget: 'image' }
      - { label: 'Image alt text', name: 'image_alt', widget: 'string' }
      - { label: 'Content', name: 'body', widget: 'markdown' }
